# Generated by Django 4.2.6 on 2023-10-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='propoerty',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='property.property'),
            preserve_default=False,
        ),
    ]
