# Generated by Django 4.2.6 on 2023-10-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertyimages_propoerty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='propertyimages/'),
        ),
    ]
