# Generated by Django 4.2.6 on 2023-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_image_alter_propertybook_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
