# Generated by Django 4.2.6 on 2023-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='adress',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
