# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='copyright_area',
            field=models.CharField(default='Copyright © 2023 Your Website', max_length=100),
        ),
    ]
